duration: 200
items:
  money:
    material: gold_ingot
    display_name: "&eGold Ingot"
    lore:
      - "&6Receive some money!"
    interact_commands:
      - "eco give %player% 20"
  alt_money:
    material: iron_ingot
    display_name: "&7Iron Ingot"
    lore:
      - "&8Receive some money!"
    pickup_commands:
      - "eco give %player% 10"
  colored_helmet:
    material: leather_helmet
    display_name: "&cRed Helmet"
    lore:
      - "&4A red helmet"
    color: "255,0,0"
    flags:
      - hide_attributes
      - hide_enchants
    enchantments:
      thorns: 2