name: "AngelicDrop"
version: "1.0.0"
main: "me.tylergrissom.angelicdrop.AngelicDropPlugin"

description: "Provides drop parties"
authors: ["Tyler Grissom"]
website: "https://tyler-g.net"

depend: ["WorldEdit"]

commands:
  angelicdrop:
    description: "AngelicDrop command."
    usage: "/<command> <sub> [args]"
    aliases: ["ad", "angelicdrops"]

permissions:
  angelicdrop.*:
    description: "Superpermission for AngelicDrop."
    children:
      angelicdrop.admin: "true"
      angelicdrop.user: "true"

  angelicdrop.user:
    description: "All user-facing permissions."
    children:
      angelicdrop.pickup: "true"
      angelicdrop.interact: "true"
      angelicdrop.notify: "true"
  angelicdrop.pickup:
    description: "Pick up drop party items."
  angelicdrop.interact:
    description: "Interact with drop party items."
  angelicdrop.notify:
    description: "Be notified when a drop party starts or ends."

  angelicdrop.admin:
    description: "All admin-facing permissions."
    children:
      angelicdrop.start: "true"
      angelicdrop.reload: "true"
  angelicdrop.start:
    description: "Start a drop party."
  angelicdrop.reload:
    description: "Reload AngelicDrop."